### ISSUE TITLE
`onBlur()` uses wrong type

### ISSUE THREAD

**Issue by ulken** [massierc/react-date-inputs#40]
The `onBlur()` prop uses the wrong type in two places:

```diff
export type DateInputProps = {
-  onBlur?(e: React.ChangeEvent): undefined;
+  onBlur?(e: React.FocusEvent): void;
}
```

Note: the changed return type as well.

and

```diff
- const handleGroupBlur = (e: React.ChangeEvent<HTMLDivElement>) => {
+ const handleGroupBlur = (e: React.FocusEvent<HTMLDivElement>) => {
```

**Comment by ulken** [comment]
I'd be happy to help out with all the issues I've posted, but I'm awaiting your response first.

**Comment by massierc** [comment]
Hi @ulken, thank you for opening the issues. I will take a look at them this weekend and get back to you.

**Comment by ulken** [comment]
@massierc did you manage to take a look?

Like I said, I can help out with whatever you approve of.

**Comment by massierc** [comment]
Hi @ulken, thank you for your patience. All of the opened issues are on point, happy to receive PRs 👍

**Comment by ulken** [comment]
@massierc I've addressed a few of the issues. Any chance you might be able to look through them today?
