### ISSUE TITLE
Support more React versions as peer dependency

### ISSUE THREAD

**Issue by ulken** [massierc/react-date-inputs#41]
Any reason not to support React 16 and 17 as a peer dependency? Is anything React 18-specific being used?

If 16 and/or 17 is proving to be a pain in the future, I'd find it completely motivated to drop support for them again.

```diff
  "peerDependencies": {
    "react": "16.x || 17.x || 18.x",
    "react-dom": "16.x || 17.x || 18.x"
  }
```

**Comment by massierc** [comment]
Nothing is 18 specific for now so happy to change this.
